defaults:
  - space: euclidean                    # options: euclidean, spherical, hyperbolic
  - model: vit3d                        # options: vit3d
  - augmentations: oct_classifier       # options: oct_classifier, normal, heavy
  - _self_

# ------------------ Experiment Settings ----------------
experiment: ??? # name of the experiment
fast_dev_run: True       # Set to true for a 1-epoch sanity check
seed: 42
grad_clip: 1.0
device: "cuda"

# TRAINING MODE
training_mode: "supervised" # options: supervised, contrastive and simsiam (not implemented yet)

# DATA
data:
  dataset: "nineclasses3D"
  image_size: 224
  batch_size: 1
  num_workers: 4
  pin_memory: True
  num_classes: 9

  sampling:
    name: "unique"       # used by SamplerFactory
    m_per_class: 2

# OPTIMIZER
optimizer: 
  lr: 1e-4
  weight_decay: 0.05
  warmup_epochs: 15

# TRAINER
trainer:
  epochs: 200
  eval_frequency: 2
  early_stopping_patience: 30
  resume_from: null

# ------------------ Paths ----------------
results_path: results/
model_path: ${hydra:run.dir}/models
logs_path: ${hydra:run.dir}/logs

# ------------------ Hydra Runtime Settings ----------------
hydra:
  run:
    dir: ${results_path}/${experiment}  # working directory for this run
# ------------------ Wandb ----------------

wandb:
  project: HypOPTIMA3D
  entity: 'pdarri97-johannes-kepler-universit-t-linz'
  run_name: ${experiment}
  mode: online                            # options: online, offline, disabled
  notes: ${hydra:job.override_dirname}
  resume: allow                           # 'allow' enables resuming previous runs or "never"
